services:
    db:
        image: postgres
        shm_size: 128mb
        environment:
            POSTGRES_USER: estagio
            POSTGRES_PASSWORD: nuEQATLZxrG%42Mk
            POSTGRES_DB: listatelefonica
        ports:
            - "5432:5432"
    
    adminer:
        image: adminer
        ports:
            - 8080:8080