<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net8.0\AppListaTelefonica.AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="obj\AppListaTelefonica.csproj.nuget.dgspec.json" />
    <Content Include="obj\Debug\net8.0\AppListaTelefonica.csproj.FileListAbsolute.txt" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net8.0\" />
    <Folder Include="obj\Debug\net8.0\refint\" />
    <Folder Include="obj\Debug\net8.0\ref\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="obj\AppListaTelefonica.csproj.nuget.g.props" />
    <None Include="obj\AppListaTelefonica.csproj.nuget.g.targets" />
    <None Include="obj\Debug\net8.0\AppListaTelefonica.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net8.0\AppListaTelefonica.assets.cache" />
    <None Include="obj\Debug\net8.0\AppListaTelefonica.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net8.0\AppListaTelefonica.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net8.0\Avalonia\resources" />
    <None Include="obj\Debug\net8.0\Avalonia\Resources.Inputs.cache" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>
</Project>
